# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: btsocket-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools
        python3 -m pip install .[test]
        if [ -f requirements.txt ]; then /usr/bin/python3 -m pip install -r requirements.txt; fi
    - name: Lint with pycodestyle
      run: |
        /usr/bin/python3 -m pycodestyle -v bluezero
        /usr/bin/python3 -m pycodestyle -v examples
    - name: Test with unittest
      run: |
        coverage -m unittest discover -v tests
        coverage report
